repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            - id: end-of-file-fixer
            - id: trailing-whitespace
            - id: mixed-line-ending
            - id: check-byte-order-marker
            - id: check-executables-have-shebangs
            - id: check-merge-conflict
            - id: check-symlinks
            - id: check-vcs-permalinks
            - id: debug-statements
            - id: check-yaml
              files: .*\.(yaml|yml)$
            - id: check-added-large-files
            - id: check-toml
    -   repo: https://github.com/grantjenks/blue
        rev: v0.9.1
        hooks:
            - id: blue
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.0.275
        hooks:
            - id: ruff
              args: [--fix, --exit-non-zero-on-fix]
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.4.0
        hooks:
        -   id: mypy
            args:
              [--show-error-codes]
    -   repo: https://github.com/python-poetry/poetry
        rev: "1.5.0"
        hooks:
            - id: poetry-check
            - id: poetry-lock
            - id: poetry-export
              args: ["-f", "requirements.txt", "-o", "requirements.txt"]
    -   repo: https://github.com/compilerla/conventional-pre-commit
        rev: v2.3.0
        hooks:
            - id: conventional-pre-commit
              stages: [commit-msg]
