version: '3.1'

services:
  app:
    build: .
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file: '.env'
    volumes:
      - './data:/data'

  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

volumes:
  pgdata:

