services:
  chat-app:
    build: .
    ports:
      - 9000:9000
    expose:
      - 9000
    env_file: '.env'
    volumes:
      - './data:/data'

  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5433:5432"

volumes:
  pgdata:

