[tool.poetry]
name = "livestream-chat"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
aiofiles = "^0.8.0"
Jinja2 = "^3.1.1"
httpx = "^0.22.0"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
motor = "^3.0.0"
sentry-sdk = "^1.9.0"
twitchio = "^2.6.0"

[tool.poetry.group.dev.dependencies]
blue = "^0.9.1"
isort = "^5.12.0"
xenon = "^0.9.0"
ruff = "^0.0.275"
pre-commit = "^3.3.3"
mypy = "^1.4.0"

[tool.mypy]
python_version = 3.10
warn_unused_configs = true
namespace_packages = true

[tool.ruff]
select = [
    "E", # pydocstyle
    "W", # pydocstyle
    "F", # pyflakes
    "I", # isort
    "UP", # pyupgrade
    "D", # docstrings
    "RUF", # ruff
]
line-length = 79
target-version = "py310"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
