[tool.poetry]
name = "livestream-chat"
version = "0.1.0"
description = ""
authors = ["dunossauro <mendesxeduardo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
aiofiles = "^0.8.0"
Jinja2 = "^3.1.1"
httpx = "^0.22.0"
python-dotenv = "^0.20.0"
loguru = "^0.6.0"
sentry-sdk = "^1.9.0"
twitchio = "^2.6.0"

[tool.poetry.group.dev.dependencies]
blue = "^0.9.1"
isort = "^5.10.1"
xenon = "^0.9.0"
taskipy = "^1.11.0"
ruff = "^0.0.274"
pytest-asyncio = "^0.23.2"
respx = "^0.20.2"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"

[tool.taskipy.tasks]
lint = 'isort --check app && blue --check app && ruff app'
test = 'pytest --cov=app -vv'
post_test = 'coverage html'

[tool.isort]
profile = 'black'
line_length = 79

[tool.pytest.ini_options]
pythonpath = '.'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
