"""youtube token table

Revision ID: fc15c152607f
Revises: cfce2e1c056b
Create Date: 2024-06-28 17:03:12.771253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc15c152607f'
down_revision: Union[str, None] = 'cfce2e1c056b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ytchattoken',
        sa.Column('live_id', sa.String(), nullable=False),
        sa.Column('live_token', sa.String(), nullable=False),
        sa.Column('next_token', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('live_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ytchattoken')
    # ### end Alembic commands ###
